### ISSUE TITLE
Option for displaying full path of signal

### ISSUE THREAD

**Issue by sveint** [cerebral/cerebral-debugger#18]
I'd love to see a option toggle for displaying the full path of a signal in the `Signals` tab. I have multiple signals with the same name (e.g. "routed"), and it would be nice to see the full path.

To clairify, what I'd like to toggle is between this:
```
routed
routed
routed
```
and this
```
views.overview.routed
views.analysis.routed
views.login.routed
```

**Comment by inergy** [comment]
#30

**Comment by sveint** [comment]
This is now fixed. Thanks a lot.
