### ISSUE TITLE
Add displaying the Debugger version number

### ISSUE THREAD

**Issue by hipertracker** [cerebral/cerebral-debugger#20]
It would be useful to display somewhere the debugger version number.

**Comment by henri-hulski** [comment]
Maybe we can add an `about` entry to the `Application` tab (or create an separate `Help` tab), which shows the version and maybe some more information about cerebral debugger (copyright, license, etc.).

A `Help` tab could also contain a link to the README.

**Comment by henri-hulski** [comment]
Not really a need for an additional `Help` tab. This could all fit in `Application`.
