### ISSUE TITLE
After controller.addModule later (code splitting) debugger does not show the newly added module state

### ISSUE THREAD

**Issue by cernymilan** [cerebral/cerebral-debugger#22]
When the debugger is restarted the new module state is shown.

**Comment by cernymilan** [comment]
I just found that it is working if newly added module is somewhere in subtree but not when it is root module (just under the controller)

**Comment by christianalfoni** [comment]
@JeronimoBlack Ah, yes. It is not really intended to be used on root. Please reopen if you are running on Cerebral 5 and consider this a problem :)
