### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by epszaw** [cerebral/cerebral-debugger#40]
Hello! I'm using stand-alone application. When I'm launching it and pass hostname and port, I don't know, what I must do next.
In my store configuration I define `devtools` like this:

```js
devtools: NODE_ENV === 'dev' && DevTools({
    host: 'localhost:8585',
    reconnect: true
  }),
```

`devtools` passed to controller, but it throws errors, like `Can't connect to localhost:8585, try to launch debugger on the same host and port`.

Whats wrong?

**Comment by epszaw** [comment]
```
Debugger application is not running on selected port... will reconnect automatically behind the scenes
```
The warning message.

**Comment by henri-hulski** [comment]
If host and port in controller and debugger are the same it should just work.

**Comment by epszaw** [comment]
But it's not! :disappointed:

**Comment by epszaw** [comment]
![image](https://user-images.githubusercontent.com/13414205/33186995-69481364-d09f-11e7-945c-b59f741c1dd2.png)

**Comment by henri-hulski** [comment]
I don't think it's an issue of the debugger as he works in most cases. So maybe it would be easier to track that down in [discord](https://discord.gg/0kIweV4bd2bwwsvH) where is a really helpful community. We have to know what system you use. Maybe localhost doesn't work. It's quite strange.

**Comment by corlaez** [comment]
I can't connect either: using 8585 or 8686 or localhost or my net ip or 127...
I am on ubuntu, chrome.

Note: I am using the chrome devtools cerebral 2. Is that deprecated?

**Comment by christianalfoni** [comment]
Hi there! Could you guys try using `127.0.0.1:8585` instead of localhost?

**Comment by christianalfoni** [comment]
@lamartire Could you extend your window? Cause there is an ADD button down there, do not think you see it? :)

**Comment by epszaw** [comment]
@christianalfoni oh, mate, now I'm on other os and can't reproduce it.
I used linux mint. On fedora this problem not actual.
I think in last version problem was resolved for mint too.
