### ISSUE TITLE
Regular expressions shown as {} in the state tree view

### ISSUE THREAD

**Issue by joseds** [cerebral/cerebral-debugger#41]
Hi, the debugger (version 1.5.0) shows regular expressions used when defining Cerebral form validation as `{}` instead of showing the string representation.

Example:
```js
  myForm: {
    salutationNameDE: {
      errorText: 'ungültig',
      isRequired: false,
      isValueRules: ['minLength:1'],
      validationRules: [/^[a-zA-ZäöüÄÖÜ0-9 ]*$/, 'maxLength: 10']
    }
  }
```

results in 
```js
  myForm: {
    salutationNameDE: {
      errorText: "ungültig",
      isRequired: false,
      isValueRules: ["minLength:1"],
      validationRules: [
        { },
        "maxLength: 10"
      ]
    }
  }
```
in the "STATE-TREE" debugger tab.

**Comment by christianalfoni** [comment]
Hm, this has to do with how `JSON.stringify` works. Regexps should ideally transform to its string representation on `toJSON`, but seems they do not. It would be quite an effort to make this work differently, too much for the gain I would state :)
