### ISSUE TITLE
Error when trying to change state or travel to a previous state

### ISSUE THREAD

**Issue by lbogdan** [cerebral/cerebral-debugger#57]
As discussed on Discord, while working on [CodeSandbox](https://github.com/CompuIves/codesandbox-client/) and using the debugger (which, btw, is **awesome**!), I've noticed that when I try to edit the state, or travel to a previous state, I get this error in the browser and nothing happens:
```
Uncaught TypeError: this.state.runInBatch is not a function
    at Model.updateIn (Model.js:89)
    at Model.set (Model.js:141)
    at Devtools.onMessage (index.js:141)
```

**Comment by christianalfoni** [comment]
@lbogdan Man, HI THERE :D 

I do not think this is an issue anymore :)

Please reopen if it is
