### ISSUE TITLE
Cannot connect to application

### ISSUE THREAD

**Issue by Nodios** [cerebral/cerebral-debugger#61]
I've created React app using _create_react_app_ and tried to connect it to a debugger. App is running on _localhost:8585_ and once I try to attach debugger to the address, debugger just displays empty state, no sequences, etc and if I refresh the page, I get the message _Upgrade required_ on the page. Any clue what to do? 

I tried to connect to app using _127.0.0.1:8585_ as well, but the same occurs.

Packages:
cerebral: latest
@cerebral/react: 4.0.1
react: 16.6.0
react-dom: 16.6.0
react-scripts: 2.0.5

Debugger: 3.0.0

OSX High Sierra 10.13.3

**Comment by christianalfoni** [comment]
Could you try using your local IP to connect? Not just 127... but actual IP?

**Comment by Nodios** [comment]
Not working

**Comment by christianalfoni** [comment]
Though 8585, might be something else running there? Have you tried changing the port?

**Comment by Nodios** [comment]
Yes, tried 3000 and 8686

**Comment by christianalfoni** [comment]
IS this how your page looks? https://stackoverflow.com/questions/35698061/why-node-js-requires-an-upgrade-while-trying-to-run-an-application-on-the-localh

Are you running the app on the same port as the devtools? They should be different ports :)

**Comment by Nodios** [comment]
Yeah, but how should I run it on the different port than the app?

**Comment by christianalfoni** [comment]
When you add an app in the debugger application you choose the port. Choose a port that is different from your app :)

Then use that port in the devtools configuration of your app.

https://cerebraljs.com/docs/introduction/devtools.html

**Comment by Nodios** [comment]
Well, that was super obvious! Thanks, it works as expected

**Comment by christianalfoni** [comment]
Great :)
