### ISSUE TITLE
Cerebral Debugger is not starting up properly

### ISSUE THREAD

**Issue by asmundwego** [cerebral/cerebral-debugger#62]
I just installed the Cerebral Debugger on my Windows 10 computer. 
When starting up, the program is just showing the brain logo in the middle with the text "Loading..." on the side. 
It also opens a chromium devtools at the side with this error in the Console: 

    Failed to load resource: net::ERR_CONNECTION_REFUSED

If I press CTRL+R to reload, it shows:

    GET http://localhost:9000/dist/bundle.js net::ERR_CONNECTION_REFUSED

![cerebral_debugger_2018-11-27_11-00-11](https://user-images.githubusercontent.com/14922923/49073856-afb61600-f233-11e8-9e81-4addc9f4e273.png)

**Comment by asmundwego** [comment]
OK, I found out what's wrong. A collegue of mine found this code line in source of your app:

    app.src = process.env.NODE_ENV !== 'development' ? './build/bundle.js' : 'http://localhost:9000/dist/bundle.js';

It seems I had stored NODE_ENV as a user environment variable in windows. I deleted that, and now it works.

**Comment by christianalfoni** [comment]
Glad to hear you figured it out @asmundwego , sorry for extremely late reply :)
